#!/bin/sh

set -e

case "$1" in
	purge)
		rm -rv /var/log/account
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`$1'" >&2
		;;
esac

# Automatically added by dh_installinit/10.6.4ubuntu1
if [ "$1" = "purge" ] ; then
	update-rc.d acct remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


exit 0
