#!/bin/sh

set -e

case "$1" in
	configure)
		mkdir -p /var/log/account
		touch /var/log/account/pacct
		chmod 0640 /var/log/account/pacct*
		chown root:adm /var/log/account/pacct*
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		;;
esac

# Automatically added by dh_installinit/10.6.4ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/acct" ]; then
		update-rc.d acct start 20 2 3 4 5 . stop 20 1 . >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d acct $_dh_action || exit $?
	fi
fi
# End automatically added section


exit 0
